"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _task_abstraccion from './task-abstraccion.bones.json'
import _task_ikigai from './task-ikigai.bones.json'

registerBones({
  "task-abstraccion": _task_abstraccion,
  "task-ikigai": _task_ikigai,
})
